# Generated by Django 2.2.5 on 2019-09-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000, verbose_name='Описание')),
                ('status', models.CharField(default='new', max_length=300, verbose_name='Статус')),
                ('date', models.DateField(blank=True, default='', null=True, verbose_name='Дата выполнения')),
            ],
        ),
    ]
