# Generated by Django 2.2.5 on 2019-09-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190909_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_description',
            field=models.TextField(default='', max_length=3000, verbose_name='Подробное Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=3000, verbose_name='Описание'),
        ),
    ]
