# Generated by Django 2.2.5 on 2019-09-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190909_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='total_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Подробное Описание'),
        ),
    ]
